Vacancy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from pytils.translit import slugify
from time import time


def gen_slug(slug):
    new_slug = slugify(slug)
    return new_slug


class Vacancy(models.Model):

    title = models.CharField('Название вакансии', max_length=100)
    slug = models.SlugField(max_length=100)
    specialty = models.ForeignKey(
        'Specialty', related_name='vacancies', verbose_name='Специализация', on_delete=models.CASCADE
    )
    company = models.ForeignKey(
        'Company', related_name='vacancies', verbose_name='Компания', on_delete=models.CASCADE
    )
    skills = models.CharField('Навыки', max_length=100)
    description = models.TextField('Текст')
    salary_min = models.PositiveIntegerField('Зарплата от')
    salary_max = models.PositiveIntegerField('Зарплата до')
    published_at = models.DateField('Опубликовано', auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        verbose_name = 'Вакансия'
        verbose_name_plural = 'Вакансии'
        ordering = ["-published_at"]

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = gen_slug(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("detail_vacancy_url", kwargs={'slug': self.slug})


class Specialty(models.Model):
    SPECIALTY_CHOICES = [
        (None, 'Выбор специальности'),
        ('frontend', 'Фронтенд'),
        ('backend', 'Бэкенд'),
        ('gamedev', 'Геймдев'),
        ('devops', 'Девопс'),
        ('design', 'Дизайн'),
        ('products', 'Продукты'),
        ('management', 'Менеджмент'),
        ('testing', 'Тестирование'),
    ]

    CODE_CHOICES = [
        (None, 'Выбор кода специальности'),
        ('frontend', 'frontend'),
        ('backend', 'backend'),
        ('gamedev', 'gamedev'),
        ('devops', 'devops'),
        ('design', 'design'),
        ('products', 'products'),
        ('management', 'management'),
        ('testing', 'testing'),
    ]

    code = models.CharField('Код', max_length=100, choices=CODE_CHOICES)
    title = models.CharField('Название специальности', max_length=100, choices=SPECIALTY_CHOICES)
    pictures = models.ImageField('Картинка', upload_to='specialty/')

    class Meta:
        verbose_name = 'Специальность'
        verbose_name_plural = 'Специальности'

    def __str__(self):
        return self.code


class Company(models.Model):
    title = models.CharField('Название компании', max_length=100)
    slug = models.SlugField(max_length=100)
    location = models.CharField('Город', max_length=100)
    logo = models.ImageField('Логотип', upload_to='company_logo/', blank=True)
    description = models.TextField('Текст')
    employee_count = models.PositiveSmallIntegerField('Количество сотрудников')
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        verbose_name = 'Компания'
        verbose_name_plural = 'Компании'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = gen_slug(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("detail_company_url", kwargs={'slug': self.slug})


class Resume(models.Model):
    READY_TO_WORK_CHOICES = [
        ('NOT', 'Не ищу работу'),
        ('OPEN', 'Открыт к предложениям'),
        ('LOOK', 'Ищу работу'),
    ]
    GRADE_CHOICES = [
        ('IN', 'Стажер (intern)'),
        ('JR', 'Младший (junior)'),
        ('ML', 'Средний (middle)'),
        ('SR', 'Старший (senior)'),
        ('LD', 'Ведущий (Lead)'),
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField('Имя', max_length=100)
    slug = models.SlugField(max_length=100)
    surname = models.CharField('Фамилия', max_length=100)
    status = models.CharField('Готовность к работе', max_length=100, choices=READY_TO_WORK_CHOICES, default='NOT')
    grade = models.CharField('Квалификация', max_length=100, choices=GRADE_CHOICES, default='IN')
    salary = models.PositiveIntegerField('Вознаграждение')
    specialty = models.ForeignKey(Specialty, on_delete=models.DO_NOTHING, verbose_name='Специализация', default='frontend')
    education = models.TextField('Образование')
    experience = models.TextField('Опыт работы')
    portfolio = models.CharField('Ссылка на портфолио', max_length=250, blank=True)

    class Meta:
        verbose_name = 'Портфолио'
        verbose_name_plural = 'Портфолио'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = str(time()).split('.')[0] + str(time()).split('.')[1] + str(self.user.id)
        super().save(*args, **kwargs)


class Application(models.Model):
    username = models.CharField('Имя', max_length=150)
    phone = models.PositiveBigIntegerField('Номер телефона')
    letter = models.TextField('Сопроводительное письмо')
    vacancy = models.ForeignKey(Vacancy, on_delete=models.DO_NOTHING)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Отклик'
        verbose_name_plural = 'Отклики'

    def __str__(self):
        return self.username

templates/main/all_vacancy.html
{% extends 'main/base.html' %}

{% block title %}
    Список всех вакансий
{% endblock %}
{% block content %}
    <section>
      <h2 class="h1 text-center mx-auto mt-4 pt-5" style="font-size: 70px;"><strong>Все вакансии</strong></h2>
      <p class="text-center pt-1">{{ object_list.count }} вакансий</p>
      <div class="row mt-5">
        <div class="col-12 col-lg-8 offset-lg-2 m-auto">
            {% for vac in object_list %}
              <div class="card mb-4">
                <div class="card-body px-4">
                  <div class="row">
                    <div class="col-12 col-md-8 col-lg-9">
                      <h2 class="h2 pb-2">{{ vac.title }}</h2>
                      <p class="mb-2">
                          {{ vac.skills }}
                      </p>
                      <p>От {{ vac.salary_min }} до {{ vac.salary_max}} руб.</p>
                      <p class="text-muted pt-1">{{ vac.published_at|date:"F, d" }}</p>
                    </div>
                    <div class="col-12 col-md-4 col-lg-3 d-flex align-items-end">
                      <a href="{% url 'detail_vacancy_url' vac.slug %}"><img src="{{ vac.company.logo.url }}" width="130" height="80" alt=""></a>
                    </div>
                  </div>
                </div>
              </div>
                {% empty %}
                    <h2 class="h1 text-center mx-auto mt-4 pt-5" style="font-size: 70px;">Вакансий пока нет</h2>
            {% endfor %}
        </div>
      </div>
    </section>

{% endblock %}

templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>
  <meta charset="UTF-8">
  <title>{% block title %}Джуманджи{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
  <header class="container mt-3">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand mr-4" href="{% url 'main' %}">Джуманджи</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
        <ul class="navbar-nav col-10">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'all_vacancy' %}">Вакансии</a>
          </li>

        </ul>
         <ul class="navbar-nav col-2 justify-content-end">
          <li class="nav-item active">
            <div class="btn-group">
                {% if request.user.is_authenticated %}
                  <button type="button" class="btn dropdown-toggle font-weight-bold" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ request.user.first_name }} {{ request.user.last_name }}
                  </button>
                  <div class="dropdown-menu dropdown-menu-right mt-3">
                    <a href="#" class="dropdown-item py-2">Профиль</a>
                    <a href="{% if request.user.resume_set.exists %}{% url 'update_resume_url' slug=request.user.resume_set.first.slug %}{% else %}{% url 'empty_resume_url' %}{% endif %}" class="dropdown-item py-2">Резюме</a>
                    <a href="{% if  request.user.company_set.first %}{% url 'update_company_url' slug=request.user.company_set.first.slug %}{% else %}{% url 'empty_company_url' %}{% endif %}" class="dropdown-item py-2">Компания</a>
                    <a href="{% url 'logout' %}" class="dropdown-item py-2">Выйти</a>
                  </div>
                {% else %}
                    <a href="{% url 'login' %}" class="nav-link font-weight-bold">Вход</a>
                {% endif %}
            </div>
          </li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container mt-3">
      {% block content %}

      {% endblock %}
  </main>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/main/company_detail.html
{% extends 'main/base.html' %}

{% block title %}
    {{ company.title }}
{% endblock %}

{% block content %}

    <div class="navbar mt-5">
      <p><a href="{% url 'main' %}">Назад</a></p>
    </div>
    <section>
      <div class="text-center">
        <img src="{{ company.logo.url }}" width="130" height="80" alt="">
      </div>
      <h1 class="h1 text-center mx-auto mt-0 pt-1" style="font-size: 70px;"><strong>{{ company.title|title }}</strong></h1>
      <p class="text-center pt-1">Компания, {{ company.location }}, {% if company.vacancies.count == 1 %}{{ company.vacancies.count }} вакансия{% else %}{{ company.vacancies.count }} вакансий{% endif %}</p>
    {% for com in vacancy %}


      <div class="row mt-5">
        <div class="col-12 col-lg-8 offset-lg-2 m-auto">
          <div class="card mb-4">
            <div class="card-body px-4">
              <div class="row">
                <div class="col-12 col-md-8 col-lg-9">
                  <h2 class="h2 pb-2">{{ com.title }}</h2>
                  <p class="mb-2">{{ com.skills }}</p>
                  <p>От {{ com.salary_min }} до {{ com.salary_max }} руб.</p>
                  <p class="text-muted pt-1">{{ com.published_at|date:"F, d" }}</p>
                </div>
                  {% if object.logo %}
                    <div class="col-12 col-md-4 col-lg-3 d-flex align-items-end">
                        <a href="{% url 'detail_vacancy_url' slug=com.slug %}" ><img src="{{ object.logo.url }}" width="130" height="80" alt=""></a>
                    </div>
                  {% else %}
                    LOGO
                  {% endif %}
              </div>
            </div>
          </div>

        </div>
      </div>

    {% endfor %}
    </section>

{% endblock %}

templates/main/index.html
{% extends 'main/base.html' %}

{% block title %}
    {{ block.super }}
{% endblock %}

{% block content %}
    <section>
      <h1 class="h1 text-center mx-auto mt-4 py-5"><strong>Вакансии для <br>Junior-разработчиков</strong></h1>
      <div class="row">
        <div class="col-12 col-md-8 col-lg-6 offset-lg-3 offset-md-2">

          <form class="form-inline mb-3" enctype="multipart/form-data" action="{% url 'main' %}">
            <div class="form-group col-8 col-md-10 pl-0">
              <input class="form-control w-100" type="search" placeholder="Найти работу или стажировку" aria-label="Найти работу или стажировку" name="search">
            </div>
            <div class="form-group col-4 col-md-2 pl-0">
              <button class="btn btn-primary w-100" type="submit">Найти</button>
            </div>
          </form>

        </div>
      </div>
    </section>

    <section class="mt-5 pt-3">
    <h2 class="h2 font-weight-normal text-center mb-5">Вакансии по рубрикам</h2>
    <div class="row mb-0">
        {% for rubr in rubric %}

                <div class="col-6 col-md-6 col-lg-3">
                  <div class="card pt-4 text-center mb-4">
                    <img class="mx-auto d-block" src="{{ rubr.pictures.url }}" width="80" height="80" alt="">
                    <div class="card-body">
                      <p class="card-text mb-2">{{ rubr.title }}</p>
                      <p class="card-text"><a href="{% url 'list_vacancy_url' rubr.title %}">{{ rubr.vacancies.count }} вакансий</a></p>
                    </div>
                  </div>
                </div>

        {% endfor %}
    </div>

    </section>
    <section class="my-5 pt-3">
      <h2 class="h2 font-weight-normal text-center mb-5">Нам доверяют лучшие компании</h2>
      <div class="row mb-0">
          {% for com in company %}
            <div class="col-6 col-md-6 col-lg-3">
              <div class="card pt-4 text-center mb-4">
                <a href="#" style="max-width: 150px;" class="mx-auto d-block">
                  <img class="mx-auto d-block mw-100" src="{{ com.logo.url }}" alt="">
                </a>
                <div class="card-body">
                  <p class="card-text"><a href="{% url 'detail_company_url' com.slug %}">{{ com.vacancies.count }} вакансий</a></p>
                </div>
              </div>
            </div>
        {% endfor %}
      </div>
    </section>

{% endblock %}

templates/main/result_list.html
{% extends 'main/base.html' %}

{% block title %}
    Список вакансий по критериям
{% endblock %}
{% block content %}
    <section>
      <h2 class="h1 text-center mx-auto mt-4 pt-5" style="font-size: 70px;"><strong>Все вакансии</strong></h2>
      <p class="text-center pt-1">{{ result.count }} вакансий</p>
      <div class="row mt-5">
        <div class="col-12 col-lg-8 offset-lg-2 m-auto">
            {% for vac in result.all %}
              <div class="card mb-4">
                <div class="card-body px-4">
                  <div class="row">
                    <div class="col-12 col-md-8 col-lg-9">
                      <h2 class="h2 pb-2">{{ vac.title }}</h2>
                      <p class="mb-2">
                          {{ vac.skills }}
                      </p>
                      <p>От {{ vac.salary_min }} до {{ vac.salary_max}} руб.</p>
                      <p class="text-muted pt-1">{{ vac.published_at|date:"F, d" }}</p>
                    </div>
                    <div class="col-12 col-md-4 col-lg-3 d-flex align-items-end">
                      <a href="{% url 'detail_vacancy_url' vac.slug %}"><img src="{{ vac.company.logo.url }}" width="130" height="80" alt=""></a>
                    </div>
                  </div>
                </div>
              </div>
                {% empty %}
                    <h2 class="h1 text-center mx-auto mt-4 pt-5" style="font-size: 70px;">Подходящих вакансий не найдено</h2>
            {% endfor %}
        </div>
      </div>
    </section>

{% endblock %}

templates/main/vacancy_detail.html
{% extends 'main/base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block title %}
    Вакансия {{ vacancy.title }}
{% endblock %}
{% block content %}

    <div class="row mt-5">
      <div class="col-12 col-lg-2">
        <div class="pl-3 mb-5">
          <p><a href="{% url 'list_vacancy_url' slug=vacancy.specialty %}">Назад</a></p>
        </div>
      </div>
      <div class="col-12 col-lg-8">
        <section class="pl-3">
          <a href="#"><img src="{{ vacancy.company.logo.url }}" width="130" height="80" alt=""></a>
          <div class="d-flex align-items-baseline align-content-baseline">
            <h1 class="h2 mt-4 font-weight-bold" >{{ vacancy.title }}</h1>
            <p class="m-0 pl-3">{{ vacancy.salary_min }} – {{ vacancy.salary_max }} Р</p>
          </div>
          <p class="mt-2">{{ vacancy.skills }}</p>
          <p class="text-muted mb-4">{{ vacancy.company|title }} ({{ vacancy.company.employee_count }} человек), {{ vacancy.company.location }}</p>
          <div style="line-height: 1.8;">
            {{ vacancy.description|safe|linebreaks }}
          </div>
          <form action="" class="card mt-4 mb-3" enctype="multipart/form-data" method="post">
            <div class="card-body mx-3">
              <p class="h5 mt-3 font-weight-normal">Отозваться на вакансию</p>
                {% csrf_token %}
                {{ form|crispy }}
              <input type="submit" class="btn btn-primary mt-4 mb-2" value="Записаться на пробный урок">
            </div>
          </form>
        </section>
      </div>
    </div>

{% endblock %}

templates/main/vacancy_list.html
{% extends 'main/base.html' %}

{% block title %}
    {{ spec }}
{% endblock %}
{% block content %}
    <section>
      <h1 class="h1 text-center mx-auto mt-4 pt-5" style="font-size: 70px;"><strong>{{ spec }}</strong></h1>
      <p class="text-center pt-1">{{ vacancies.count }} вакансий</p>
      <div class="row mt-5">
        <div class="col-12 col-lg-8 offset-lg-2 m-auto">
            {% for vac in vacancies %}
              <div class="card mb-4">
                <div class="card-body px-4">
                  <div class="row">
                    <div class="col-12 col-md-8 col-lg-9">
                      <h2 class="h2 pb-2">{{ vac.title }}</h2>
                      <p class="mb-2">
                          {{ vac.skills }}
                      </p>
                      <p>От {{ vac.salary_min }} до {{ vac.salary_max}} руб.</p>
                      <p class="text-muted pt-1">{{ vac.published_at|date:"F, d" }}</p>
                    </div>
                    <div class="col-12 col-md-4 col-lg-3 d-flex align-items-end">
                      <a href="{% url 'detail_vacancy_url' vac.slug %}"><img src="{{ vac.company.logo.url }}" width="130" height="80" alt=""></a>
                    </div>
                  </div>
                </div>
              </div>
                {% empty %}
                    <h2 class="h1 text-center mx-auto mt-4 pt-5" style="font-size: 70px;">Вакансий пока нет</h2>
            {% endfor %}
        </div>
      </div>
    </section>

{% endblock %}