Vacancy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from pytils.translit import slugify
from time import time


def gen_slug(slug):
    new_slug = slugify(slug)
    return new_slug


class Vacancy(models.Model):

    title = models.CharField('Название вакансии', max_length=100)
    slug = models.SlugField(max_length=100)
    specialty = models.ForeignKey(
        'Specialty', related_name='vacancies', verbose_name='Специализация', on_delete=models.CASCADE
    )
    company = models.ForeignKey(
        'Company', related_name='vacancies', verbose_name='Компания', on_delete=models.CASCADE
    )
    skills = models.CharField('Навыки', max_length=100)
    description = models.TextField('Текст')
    salary_min = models.PositiveIntegerField('Зарплата от')
    salary_max = models.PositiveIntegerField('Зарплата до')
    published_at = models.DateField('Опубликовано', auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        verbose_name = 'Вакансия'
        verbose_name_plural = 'Вакансии'
        ordering = ["-published_at"]

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = gen_slug(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("detail_vacancy_url", kwargs={'slug': self.slug})


class Specialty(models.Model):
    SPECIALTY_CHOICES = [
        (None, 'Выбор специальности'),
        ('frontend', 'Фронтенд'),
        ('backend', 'Бэкенд'),
        ('gamedev', 'Геймдев'),
        ('devops', 'Девопс'),
        ('design', 'Дизайн'),
        ('products', 'Продукты'),
        ('management', 'Менеджмент'),
        ('testing', 'Тестирование'),
    ]

    CODE_CHOICES = [
        (None, 'Выбор кода специальности'),
        ('frontend', 'frontend'),
        ('backend', 'backend'),
        ('gamedev', 'gamedev'),
        ('devops', 'devops'),
        ('design', 'design'),
        ('products', 'products'),
        ('management', 'management'),
        ('testing', 'testing'),
    ]

    code = models.CharField('Код', max_length=100, choices=CODE_CHOICES)
    title = models.CharField('Название специальности', max_length=100, choices=SPECIALTY_CHOICES)
    pictures = models.ImageField('Картинка', upload_to='specialty/')

    class Meta:
        verbose_name = 'Специальность'
        verbose_name_plural = 'Специальности'

    def __str__(self):
        return self.code


class Company(models.Model):
    title = models.CharField('Название компании', max_length=100)
    slug = models.SlugField(max_length=100)
    location = models.CharField('Город', max_length=100)
    logo = models.ImageField('Логотип', upload_to='company_logo/', blank=True)
    description = models.TextField('Текст')
    employee_count = models.PositiveSmallIntegerField('Количество сотрудников')
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        verbose_name = 'Компания'
        verbose_name_plural = 'Компании'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = gen_slug(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("detail_company_url", kwargs={'slug': self.slug})


class Resume(models.Model):
    READY_TO_WORK_CHOICES = [
        ('NOT', 'Не ищу работу'),
        ('OPEN', 'Открыт к предложениям'),
        ('LOOK', 'Ищу работу'),
    ]
    GRADE_CHOICES = [
        ('IN', 'Стажер (intern)'),
        ('JR', 'Младший (junior)'),
        ('ML', 'Средний (middle)'),
        ('SR', 'Старший (senior)'),
        ('LD', 'Ведущий (Lead)'),
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField('Имя', max_length=100)
    slug = models.SlugField(max_length=100)
    surname = models.CharField('Фамилия', max_length=100)
    status = models.CharField('Готовность к работе', max_length=100, choices=READY_TO_WORK_CHOICES, default='NOT')
    grade = models.CharField('Квалификация', max_length=100, choices=GRADE_CHOICES, default='IN')
    salary = models.PositiveIntegerField('Вознаграждение')
    specialty = models.ForeignKey(Specialty, on_delete=models.DO_NOTHING, verbose_name='Специализация', default='frontend')
    education = models.TextField('Образование')
    experience = models.TextField('Опыт работы')
    portfolio = models.CharField('Ссылка на портфолио', max_length=250, blank=True)

    class Meta:
        verbose_name = 'Портфолио'
        verbose_name_plural = 'Портфолио'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = str(time()).split('.')[0] + str(time()).split('.')[1] + str(self.user.id)
        super().save(*args, **kwargs)


class Application(models.Model):
    username = models.CharField('Имя', max_length=150)
    phone = models.PositiveBigIntegerField('Номер телефона')
    letter = models.TextField('Сопроводительное письмо')
    vacancy = models.ForeignKey(Vacancy, on_delete=models.DO_NOTHING)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Отклик'
        verbose_name_plural = 'Отклики'

    def __str__(self):
        return self.username

templates/vacancy/create_list.html
{% extends 'main/base.html' %}

{% block title %}
    Список моих вакансий
{% endblock %}

{% block content %}
     <div class="row mt-5">
      <div class="col-12 col-lg-4">
        <aside class="pt-3 pb-4 px-4 mb-5 card">
          <h1 class="h4 pt-2 pb-2">Моя компания</h1>
          <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
            <a class="nav-link" href="{% url 'update_company_url' slug=request.user.company_set.first.slug %}">1. Информация о&nbsp;компании</a>
            <a class="nav-link active" href="{% url 'create_vacancy_url' %}">2. Вакансии</a>
          </div>
        </aside>
      </div>
      <div class="col-12 col-lg-8">
        <div class="card">
          <div class="card-body px-4 pb-4">
            <section class="tab-pane fade show active">
              <h2 class="h4 pt-2 pb-3">Вакансии</h2>
              <!-- vacancy state 1 -->
                {% if request.user.company_set.first  %}
                    {% for vac in vacancy %}
                        <div class="card mt-3">
                        <div class="card-body px-4">
                          <div class="row align-items-center">
                            <div class="col-6 col-lg-8">
                              <a href="{{ vac.get_absolute_url }}" class="mb-1">{{ vac.title }}</a>
                              <p class="mb-1">
                                <span class="mr-4">{{ vac.salary_max }}</span><a href="#" class="text-info">{{ vac.application_set.count }} отклика</a>
                              </p>
                            </div>
                            <div class="col-6 col-lg-4 text-right">
                              <a href="{% url 'update_vacancy_url' slug=vac.slug %}" class="btn btn-outline-info">Изменить</a>
                            </div>
                          </div>
                        </div>
                      </div>
                        <div class="mt-3">

                        </div>
                    {% endfor %}
                    <div class="form-group">
                        <a class="btn btn-outline-info" href="{% url 'create_vacancy_url' %}">Добавить вакансию</a>
                    </div>
                {% else %}
                    <div class="alert alert-primary" role="alert">
                        У вас пока нет вакансий
                    </div>
                    <div class="form-group">
                        <a class="btn btn-outline-info" href="{% url 'create_vacancy_url' %}">Добавить вакансию</a>
                    </div>
                {% endif %}
            </section>
          </div>
        </div>
      </div>
    </div>


{% endblock %}

templates/vacancy/create_vacancy.html
{% extends 'main/base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block title %}
    Создание вакансии
{% endblock %}

{% block content %}
     <div class="row mt-5">
      <div class="col-12 col-lg-4">
        <aside class="pt-3 pb-4 px-4 mb-5 card">
          <h1 class="h4 pt-2 pb-2">Моя компания</h1>
          <div class="nav flex-column nav-pills">
            <a class="nav-link" href="{% url 'update_company_url' slug=request.user.company_set.first.slug %}">1. Информация о&nbsp;компании</a>
            <a class="nav-link active" href="{% url 'create_vacancy_url' %}">2. Вакансии</a>
          </div>
        </aside>
      </div>
      <div class="col-12 col-lg-8">
        <div class="card">
          <div class="card-body px-4 pb-4 tab-content">
            <!-- Tab -->
            <section>
              <h2 class="h4 pt-2 pb-3">{{ request.user.company_set.first.title }}</h2>
              <form method="post" enctype="multipart/form-data">

                <div class="row">
                  <div class="col-12 col-md-6">
                    <div class="form-group pb-2">
                     {{ form.title|as_crispy_field }}
                    </div>
                  </div>
                    {% csrf_token %}
                  <div class="col-12 col-md-6">
                    <div class="form-group pb-2">
                      {{ form.specialty|as_crispy_field }}
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-12 col-md-6">
                    <div class="form-group pb-2">
                      {{ form.salary_min|as_crispy_field }}
                    </div>
                  </div>
                  <div class="col-12 col-md-6">
                    <div class="form-group pb-2">
                      {{ form.salary_max|as_crispy_field }}
                    </div>
                  </div>
                </div>
                <div class="form-group pb-2">
                  {{ form.skills|as_crispy_field }}
                </div>
                <div class="form-group pb-2">
                  {{ form.description|as_crispy_field }}
                </div>
                <div class="form-group">
                  <input type="submit" class="btn btn-info" value="Сохранить">
                </div>
              </form>
              <!-- END Vacancy info -->
              <!-- Applications -->
              <h2 class="h4 pt-2 pb-3">Отклики - 2</h2>
              <!-- Application 1 -->
              <div class="card mt-3">
                <div class="card-body px-4">
                  <p class="mb-1 font-weight-bold">Семёнов Зельфик Геннадиевич</p>
                  <p class="mb-2"><a href="tel:+79002842324" class="text-dark">+7 (900) 284-23-24</a></p>
                  <p class="mb-1">Я&nbsp;хотел&nbsp;бы работать в&nbsp;компании &laquo;АБВГД&raquo; программистом мобильных приложений. Мой опыт работы в&nbsp;программировании около 4&nbsp;лет (последние 1,5 года занимаюсь разработкой приложений.</p>
                </div>
              </div>
              <!-- END Application 1 -->
              <!-- Application 1 -->
              <div class="card mt-3">
                <div class="card-body px-4">
                  <p class="mb-1 font-weight-bold">Сорокина Акра Павловна</p>
                  <p class="mb-2"><a href="tel:+79002842324" class="text-dark">+7 (900) 284-23-24</a></p>
                  <p class="mb-1">Добрый день! Увидела объявление о&nbsp;вашей вакансии. Заранее благодарю Вас за&nbsp;уделенное моей кандидатуре время. С&nbsp;уважением.</p>
                </div>
              </div>
              <!-- END Application 1 -->
              <!-- END Applications -->
            </section>
            <!-- END Tab -->
          </div>
        </div>
      </div>
    </div>
{% endblock %}

templates/vacancy/vacancy_update.html
{% extends 'main/base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block title %}
    Создание вакансии
{% endblock %}

{% block content %}
     <div class="row mt-5">
      <div class="col-12 col-lg-4">
        <aside class="pt-3 pb-4 px-4 mb-5 card">
          <h1 class="h4 pt-2 pb-2">Моя компания</h1>
          <div class="nav flex-column nav-pills">
            <a class="nav-link" href="{% url 'update_company_url' slug=request.user.company_set.first.slug %}">1. Информация о&nbsp;компании</a>
            <a class="nav-link active" href="{% url 'create_vacancy_url' %}">2. Вакансии</a>
          </div>
        </aside>
      </div>
      <div class="col-12 col-lg-8">
        <div class="card">
          <div class="card-body px-4 pb-4 tab-content">
            <!-- Tab -->
            <section>
              <h2 class="h4 pt-2 pb-3">{{ request.user.company_set.first.title }}</h2>
              <form method="post" enctype="multipart/form-data">

                <div class="row">
                  <div class="col-12 col-md-6">
                    <div class="form-group pb-2">
                     {{ form.title|as_crispy_field }}

                    </div>
                  </div>
                    {% csrf_token %}
                  <div class="col-12 col-md-6">
                    <div class="form-group pb-2">
                      {{ form.specialty|as_crispy_field }}
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-12 col-md-6">
                    <div class="form-group pb-2">
                      {{ form.salary_min|as_crispy_field }}
                    </div>
                  </div>
                  <div class="col-12 col-md-6">
                    <div class="form-group pb-2">
                      {{ form.salary_max|as_crispy_field }}
                    </div>
                  </div>
                </div>
                <div class="form-group pb-2">
                  {{ form.skills|as_crispy_field }}
                </div>
                <div class="form-group pb-2">
                  {{ form.description|as_crispy_field }}
                </div>
                <div class="form-group">
                  <input type="submit" class="btn btn-info" value="Сохранить">
                </div>
              </form>
              <!-- END Vacancy info -->
              <!-- Applications -->
              <h2 class="h4 pt-2 pb-3">Отклики - {{ vacancy.application_set.count }}</h2>
              <!-- Application 1 -->
                {% for foo in vacancy.application_set.all %}
                    <div class="card mt-3">
                        <div class="card-body px-4">
                            <p class="mb-1 font-weight-bold">{{ foo.username }}</p>
                            <p class="mb-2"><a href="tel:+79002842324" class="text-dark">{{ foo.phone }}</a></p>
                            <p class="mb-1">{{ foo.letter }}</p>
                        </div>
                    </div>
                {% endfor %}
            </section>
            <!-- END Tab -->
          </div>
        </div>
      </div>
    </div>
{% endblock %}